# Dato de referencia estático usado por transform() en etl.py.
# Se mantiene separado de la lógica de pipeline porque cambia por razones
# distintas: agregar un país o afinar una keyword no es un cambio de
# comportamiento del ETL, es actualizar una tabla de consulta.

# Palabras clave que identifican un título de trabajo como relacionado a
# datos/IA/ML/BI. El dataset ampliado (foorilla/ai-jobs-net-salaries)
# incluye títulos genéricos de tecnología (Software Engineer, Manager,
# Analyst, Developer, Architect...) sin calificador de datos/IA, que se
# excluyen para mantener el alcance del proyecto ("Data Science Salaries").
DATA_ROLE_KEYWORDS = [
    "data",
    "analytics",
    "scientist",
    "machine learning",
    " ml ",
    "ai engineer",
    "ai scientist",
    "ai product",
    "ai lead",
    "ai researcher",
    "ai architect",
    "business intelligence",
    " bi ",
    "nlp",
    "computer vision",
    "deep learning",
    "prompt engineer",
    "llm",
]

# Mapeo de país (ISO 3166 alpha-2) a continente, agrupación geográfica estándar.
CONTINENT_MAP = {
    # América del Norte (incluye Centroamérica y Caribe, convención UN geoscheme)
    "US": "North America",
    "CA": "North America",
    "MX": "North America",
    "BM": "North America",
    "PR": "North America",
    "BS": "North America",
    "JM": "North America",
    "DO": "North America",
    "CR": "North America",
    "PA": "North America",
    "HN": "North America",
    "SV": "North America",
    "GT": "North America",
    # América del Sur
    "BR": "South America",
    "AR": "South America",
    "CL": "South America",
    "CO": "South America",
    "PE": "South America",
    "EC": "South America",
    "BO": "South America",
    "VE": "South America",
    # Europa
    "GB": "Europe",
    "ES": "Europe",
    "FR": "Europe",
    "DE": "Europe",
    "IT": "Europe",
    "NL": "Europe",
    "AT": "Europe",
    "BE": "Europe",
    "BG": "Europe",
    "BA": "Europe",
    "CH": "Europe",
    "CZ": "Europe",
    "DK": "Europe",
    "EE": "Europe",
    "FI": "Europe",
    "GR": "Europe",
    "HR": "Europe",
    "HU": "Europe",
    "IE": "Europe",
    "LT": "Europe",
    "LU": "Europe",
    "LV": "Europe",
    "MD": "Europe",
    "MK": "Europe",
    "MT": "Europe",
    "NO": "Europe",
    "PL": "Europe",
    "PT": "Europe",
    "RO": "Europe",
    "RS": "Europe",
    "SE": "Europe",
    "SI": "Europe",
    "SK": "Europe",
    "UA": "Europe",
    "RU": "Europe",
    "TR": "Europe",
    "GE": "Europe",
    "AM": "Europe",
    "CY": "Europe",
    "XK": "Europe",
    "AD": "Europe",
    "GI": "Europe",
    "JE": "Europe",
    # Asia (incluye Medio Oriente)
    "IN": "Asia",
    "CN": "Asia",
    "JP": "Asia",
    "SG": "Asia",
    "HK": "Asia",
    "TW": "Asia",
    "KR": "Asia",
    "ID": "Asia",
    "MY": "Asia",
    "PH": "Asia",
    "TH": "Asia",
    "VN": "Asia",
    "PK": "Asia",
    "UZ": "Asia",
    "IL": "Asia",
    "AE": "Asia",
    "SA": "Asia",
    "QA": "Asia",
    "KW": "Asia",
    "OM": "Asia",
    "JO": "Asia",
    "LB": "Asia",
    "IQ": "Asia",
    "IR": "Asia",
    # Oceanía
    "AU": "Oceania",
    "NZ": "Oceania",
    "AS": "Oceania",
    # África
    "ZA": "Africa",
    "NG": "Africa",
    "KE": "Africa",
    "GH": "Africa",
    "TN": "Africa",
    "DZ": "Africa",
    "EG": "Africa",
    "RW": "Africa",
    "ZM": "Africa",
    "UG": "Africa",
    "ML": "Africa",
    "LS": "Africa",
    "MU": "Africa",
    "CD": "Africa",
    "CF": "Africa",
}
